"""Added several entries in QuizResult

Revision ID: 0b15f8d7c98b
Revises: 685f85b592cd
Create Date: 2025-05-25 01:17:59.710688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b15f8d7c98b'
down_revision = '685f85b592cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_answer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timstamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('timstamp')
        batch_op.drop_column('user_answer')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
