"""Added is_admin entry in User

Revision ID: 685f85b592cd
Revises: 
Create Date: 2025-05-25 01:11:04.814328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685f85b592cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
