"""Update user models

Revision ID: bd3971bbe8b6
Revises: fa449806dcc8
Create Date: 2025-05-26 00:03:20.515674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3971bbe8b6'
down_revision = 'fa449806dcc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('question')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('user_answer')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('role')
        batch_op.drop_column('username')

    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_answer', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('question', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
